# Generated by Django 3.1.4 on 2020-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20201207_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
